### PR TITLE
 Add Alpha and Symbol generation as 2 separate utility methods 

### PR DESCRIPTION
**Pull request by kishaningithub**
Added Alpha and Symbol generation as 2 separate utility methods because the project which i am working on needs those 🙂

### CODE REVIEW

**Comment by chr4** [comment]
Oh sorry, missed the documentation is already there :)

**Comment by chr4** [comment]
Looks good to me! Merging.

**Comment by kishaningithub** [comment]
@chr4 The last release 1.0.0 was made in 2014 and this gets fetched by dependency managers
https://github.com/chr4/pwgen/releases
Kindly bump up

**Comment by chr4** [comment]
Released as `v1.1.0`

**Pull request merged**
